#include <stdint.h>
#include "../include/isa-sm83.h"

const Instruction INSTRUCTIONS[] = {
    {"NOP", OPCODE_NOP, NONE, NA, NONE, NA, NOP, MISC, UNCONDITIONAL, 0, 1},
    {"LD BC,%d", OPCODE_LD_BC_D16, BC, REGISTER, D16, IMMEDIATE_MEM, LD, LD_ST_MOV, UNCONDITIONAL, 0, 3},
    {"LD (BC),A", OPCODE_LD_REF_BC_A, BC, REGISTER_INDIRECT, A, REGISTER, LD, LD_ST_MOV, UNCONDITIONAL, 0, 3},
    {"INC BC", OPCODE_INC_BC, BC, REGISTER, NONE, NA, INC, ALU, UNCONDITIONAL, 0, 1},
    {"INC B", OPCODE_INC_B, B, REGISTER, NONE, NA, INC, ALU, UNCONDITIONAL, 0, 1},
    {"DEC B", OPCODE_DEC_B, B, REGISTER, NONE, NA, DEC, ALU, UNCONDITIONAL, 0, 1},
    {"LD B,%d", OPCODE_LD_B_D8, B, REGISTER, D8, IMMEDIATE_MEM, LD, LD_ST_MOV, UNCONDITIONAL, 0 , 2},
    {"RLCA", OPCODE_RLCA, A, REGISTER, NONE, NA, RLCA, SHIFTER, UNCONDITIONAL, 0, 1},
    {"LD (%#4X),SP", OPCODE_LD_REF_A16_SP, A16, IMMEDIATE_MEM_INDIRECT, SP, REGISTER, LD, LD_ST_MOV, UNCONDITIONAL, 0, 3},
    {"ADD HL,BC", OPCODE_ADD_HL_BC, HL, REGISTER, BC, REGISTER, ADD, ALU, UNCONDITIONAL, 0, 1},
    {"LD A,(BC)", OPCODE_LD_A_REF_BC, A, REGISTER, BC, REGISTER_INDIRECT, LD, LD_ST_MOV, UNCONDITIONAL, 0, 1},
    {"DEC BC", OPCODE_DEC_BC, BC, REGISTER, NONE, NA, DEC, ALU, UNCONDITIONAL, 0, 1},
    {"INC C", OPCODE_INC_C, C, REGISTER, NONE, NA, INC, ALU, UNCONDITIONAL, 0, 1},
    {"DEC C", OPCODE_DEC_C, C, REGISTER, NONE, NA, DEC, ALU, UNCONDITIONAL, 0, 1},
    {"LD C,%d", OPCODE_LD_C_D8, C, REGISTER, D8, IMMEDIATE_MEM, LD, LD_ST_MOV, UNCONDITIONAL, 0, 2},
    {"RRCA", OPCODE_RRCA, A, REGISTER, NONE, NA, RRCA, SHIFTER, UNCONDITIONAL, 0, 1},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"JR NZ,%d", OPCODE_JR_NZ_R8, D8, IMMEDIATE_MEM, NONE, NA, JR, JUMP, NZ, 0, 2},
    {"LD HL,%d", OPCODE_LD_HL_D16, HL, REGISTER, D16, IMMEDIATE_MEM, LD, LD_ST_MOV, UNCONDITIONAL, 0, 3},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"LD (HL-),A", OPCODE_LDD_REF_HL_A, HL, REGISTER_INDIRECT, A, REGISTER, LDD, LD_ST_MOV, UNCONDITIONAL, 0, 1},
    {"INC SP", OPCODE_INC_SP, SP, REGISTER, NONE, NA, INC, ALU, UNCONDITIONAL, 0, 1},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"LD A,%d", OPCODE_LD_A_D8, A, REGISTER, D8, IMMEDIATE_MEM, LD, LD_ST_MOV, UNCONDITIONAL, 0, 2},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"XOR A", OPCODE_XOR_A, A, REGISTER, A, REGISTER, XOR, ALU, UNCONDITIONAL, 0, 1},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"JP 0x%04X", OPCODE_JP_A16, A16, IMMEDIATE_MEM, NONE, NA, JP, JUMP, UNCONDITIONAL, 0, 3},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"LDH %#2X,A", OPCODE_LDH_REF_A8_A, A8, IMMEDIATE_MEM_INDIRECT, A, REGISTER, LDH, LD_ST_MOV, UNCONDITIONAL, 0, 2},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"LDH A,%#2X", OPCODE_LDH_A_REF_A8, A, REGISTER, A8, IMMEDIATE_MEM_INDIRECT, LDH, LD_ST_MOV, UNCONDITIONAL, 0, 2},
    {"NA"},
    {"NA"},
    {"DI", OPCODE_DI, NONE, NA, NONE, NA, DI, MISC, UNCONDITIONAL, 0, 1},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"NA"},
    {"LD SP,HL", OPCODE_LD_SP_HL, SP, REGISTER, HL, REGISTER, LD, LD_ST_MOV, UNCONDITIONAL, 0, 1},
    {"NA"},
    {"EI", OPCODE_EI, NONE, NA, NONE, NA, EI, MISC, UNCONDITIONAL, 0, 1},
    {"NA"},
    {"NA"},
    {"CP %d", OPCODE_CP_D8, A, REGISTER, D8, IMMEDIATE_MEM, CP, ALU, UNCONDITIONAL, 0, 2},
    {"NA"}
};

const Instruction CB_INSTRUCTIONS[];

